### ISSUE TITLE
Нет поля MIN_LEVEL в yastations

### ISSUE THREAD

**Issue by kirush0280** [sergejey/majordomo-yadevices#1]
11:42:32 0.83474000 Error registered (type: sql):
1054: Unknown column 'MIN_LEVEL' in 'where clause'
SELECT ID FROM yastations WHERE TTS=1 AND MIN_LEVEL<=2
Backtrace:
#0 /var/www/html/lib/mysqli.class.php(399): registerError('sql', '1054: Unknown c...')
#1 /var/www/html/lib/mysqli.class.php(217): mysql->Error('SELECT ID FROM ...', 0)
#2 /var/www/html/lib/sqlFunctions.class.php(70): mysql->Select('SELECT ID FROM ...')
#3 /var/www/html/lib/common.class.php(405): SQLSelect('SELECT ID FROM ...')
#4 /var/www/html/modules/scripts/scripts.class.php(159) : eval()'d code(8): say('\xD0\x90\xD0\xB9-\xD0\xBF\xD0\xB8 \xD0\xB0\xD0\xB4\xD1...', 2)
#5 /var/www/html/modules/scripts/scripts.class.php(159): eval()
#6 /var/www/html/lib/common.class.php(885): scripts->runScript('tellIPAddress', Array)
#7 /var/www/html/modules/scripts/scripts.class.php(159) : eval()'d code(2): runScript('tellIPAddress', Array)
#8 /var/www/html/modules/scripts/scripts.class.php(159): eval()
#9 /var/www/html/lib/common.class.php(885): scripts->runScript('29', Array)
#10 /var/www/html/api.php(368): runScript('29', Array)
#11 {main}

**Comment by sergejey** [comment]
М... сейчас в коде нет вызова такого запроса, но он был раньше. Может быть что-то не до конца обновилось?

**Comment by kirush0280** [comment]
![2020-01-28_12-02-54](https://user-images.githubusercontent.com/13412942/73249584-38c53600-41c6-11ea-9988-57849d0744ce.png)
код нашел в /var/www/html/lib/common.class.php

**Comment by kirush0280** [comment]
Сборка: master

**Comment by sergejey** [comment]
"SELECT ID FROM yastations WHERE TTS=1 AND MIN_LEVEL<=2"
Именно такой код?

Попробуйте принудительно обновить этот модуль (клавиша Обновить).

**Comment by kirush0280** [comment]
Принудительно обновил:
Plugin 'yadevices' (2020-01-18 20:20:30) installed.
код остался здесь:
/var/www/html/backup_temp/lib/common.class.php:        $stations = SQLSelect("SELECT ID FROM yastations WHERE TTS=1 AND MIN_LEVEL<=".(int)$level);

**Comment by sergejey** [comment]
./backup_temp/ -- видимо это папка от какого-то модуля резервного копирования. в исполняемом коде системы такого не должно быть, так что наверное можно закрыть.
